{% set version="0.0.1c" %}
{% set tag="b7cc6fa" %}
about:
    home: https://github.com/nh13/snakeparse
    license: MIT
    summary: Making Snakemake workflows into full-fledged command line tools since 1999.
package:
    name: snakeparse
    version: {{ version }}
build:
  number: 0
  skip: false
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - snakeparse=snakeparse.__main__:main
source:
  fn: {{ tag }}.tar.gz
  url: https://github.com/nh13/snakeparse/archive/{{ tag }}.tar.gz
  sha256: 02d2df97f47ca54ce2366800850ca3d53a37076907b76ddcd8540d4303217534
requirements:
  build:
    - python
    - setuptools
    - pyhocon >=0.3.38
    - pyyaml >=3.12
  run:
    - python
    - pyhocon >=0.3.38
    - pyyaml >=3.12
test:
    imports:
        - snakeparse
