{% set version="0.0.1c" %}
{% set tag="4c5c3ed" %}
about:
    home: https://github.com/nh13/snakeparse
    license: MIT
    summary: Making Snakemake workflows into full-fledged command line tools since 1999.
package:
    name: snakeparse
    version: {{ version }}
build:
  number: 0
  skip: false
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - snakeparse=snakeparse.__main__:main
source:
  fn: {{ tag }}.tar.gz
  url: https://github.com/nh13/snakeparse/archive/{{ tag }}.tar.gz
  sha256: e12b94a8de0b4d213ca2d611ffa08d136a73345b65837d4d48d9b79071380845
requirements:
  build:
    - python
    - setuptools
    - pyhocon >=0.3.38
    - pyyaml >=3.12
  run:
    - python
    - pyhocon >=0.3.38
    - pyyaml >=3.12
test:
    imports:
        - snakeparse
