{% set pkgname = "pyhocon" %}
{% set version = "0.3.38" %}
{% set sha256 = "888b660fb86e643ded212207a1a1d260ccff293f19614e4d20d10f30621eeb26" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyhocon=pyhocon.tool:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.3

  run:
    - python
    - pyparsing >=2.0.3

test:
  imports:
    - pyhocon

  commands:
    - pyhocon --help

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  summary: 'HOCON parser for Python'

extra:
  recipe-maintainers:
    - shahin
